Add support for multi-line status messages.
Many of our Autotest test cases return multi-line status messages upon failure. Due to the regular expression used by Autotest these lines cause an "AttributeError: 'NoneType' object has no attribute 'groups'" exception to be thrown. By modifying the regular expression to allow '.' to match '\n' these errors are avoided.

I've added a new unit test, test_parse_line_handles_embedded_new_lines(), to check for these types of messages.

Change-Id: I0b3f4d90caf2cfc81724b928f6bea90eec6c38b0

BUG=7611
TEST=Ran unit tests. Ran in production system over the weekend.

Review URL: http://codereview.chromium.org/3719002