power_status: Allow other PSU besides Mains.
power_supply driver in kernel (driver/power/power_supply_sysfs.c)
provides other PSU types besides 'Mains',

        static char *type_text[] = {
                "Unknown", "Battery", "UPS", "Mains", "USB",
                "USB_DCP", "USB_CDP", "USB_ACA"
        };

This CL adds those other power supply types which are reasonable
system PSUs.

BUG=chrome-os-partner:17927
TEST=run locally on hosts connected to PSU,
  cd /usr/local/autotest
  bin/autotest tests/power_LoadTest/control.1hour

    ERROR: Running on AC power. Please remove AC power cable

Change-Id: Ib6023c351c2a06eba35afa81c32f8c72cc722871
Reviewed-on: https://gerrit.chromium.org/gerrit/44735
Reviewed-by: Sameer Nanda <snanda@chromium.org>
Commit-Queue: Todd Broch <tbroch@chromium.org>
Tested-by: Todd Broch <tbroch@chromium.org>