graphics_GLBench: remove lingering reference_images_url reference
Commit [0] removed the definition of reference_images_url, but left a
reference to it around.  Thanks python.

[0] commit 70618305450c2089806267ba54e7f23175bc44ae
graphics_GLBench: simplify known image handling.

Signed-off-by: Daniel Kurtz <djkurtz@chromium.org>

BUG=chromium:376493
TEST=Try testing on a machine where some tests fail.
  => autotest rund does not fail with:
  FAIL: Unhandled AttributeError: 'graphics_GLBench' object has no attribute 'reference_images_url'

Change-Id: I54242d466ef3ef95f59b8de1a29dde13344a0f80
Reviewed-on: https://chromium-review.googlesource.com/201823
Reviewed-by: Rohit Makasana <rohitbm@chromium.org>
Commit-Queue: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>