bluetooth_adpater_tests: fixed a bug about CoS/CoD
if device_class is None, the following exception would be raised:
  TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'

When device_class is None, the discovered class of service/class
should just be None.

BUG=chromium:610238
TEST=None

Change-Id: I42df1d54043564efb54d8f3e59844fd13bf14220
Reviewed-on: https://chromium-review.googlesource.com/359476
Commit-Ready: Shyh-In Hwang <josephsih@chromium.org>
Tested-by: Shyh-In Hwang <josephsih@chromium.org>
Reviewed-by: Cheng-Yi Chiang <cychiang@chromium.org>