Fix mental error in get_hostapd_mac
It appears this code wasn't tested before it was committed,
since it never had a chance... :-)

BUG=None
TEST=Make sure the error:
   AttributeError: 'str' object has no attribute 'Interface'
doesn't happen any more due to
   ap_interface = interface.Interface(interface, self.host)

Change-Id: I42aeedf3e47de64260a84bbb2386dff1f76f22b0
Reviewed-on: https://chromium-review.googlesource.com/186580
Reviewed-by: Christopher Wiley <wiley@chromium.org>
Commit-Queue: Paul Stewart <pstew@chromium.org>
Tested-by: Paul Stewart <pstew@chromium.org>