power: bugfix for RC6 testing on Atom devices.
Change,
   3326874 power_x86Settings: Add a test for RC6

Had an indent bug which fails for Atom platforms as:

  UnboundLocalError: local variable 'found' referenced before assignment

On systems Non-atom systems there was another failure,
  Unhandled IndexError: no such group

Due to missing parens in re.search regexp.  Thats fixed as we..

Also removed a few pesky semicolons that pylint caught and a docstring
to get past the repo verify step.

BUG=none
TEST=pylint clean for change.  Run test on lumpy

Change-Id: Ice2642b1e57462b245b7f8842a822fdb2d00e3de
Reviewed-on: https://gerrit.chromium.org/gerrit/64775
Reviewed-by: Daniel Erat <derat@chromium.org>
Commit-Queue: Todd Broch <tbroch@chromium.org>
Tested-by: Todd Broch <tbroch@chromium.org>