Experiment to find cause of import chromite error.
During repo upload, I almost always get an inport error saying:
    * Hook script "./site_utils/presubmit_hooks/check_suite_scheduler.py" failed with code 1:
      Traceback (most recent call last):
        File "./site_utils/presubmit_hooks/check_suite_scheduler.py", line 46, in <module>
          main()
        File "./site_utils/presubmit_hooks/check_suite_scheduler.py", line 39, in main
          output = utils.system_output(suite_scheduler + ' --sanity')
        File "/usr/local/google/home/scunningham/chromiumos/src/third_party/autotest/files/client/common_lib/base_utils.py", line 1043, in system_output
          args=args).stdout
        File "/usr/local/google/home/scunningham/chromiumos/src/third_party/autotest/files/client/common_lib/base_utils.py", line 740, in run
          "Command returned non-zero exit status")
      autotest_lib.client.common_lib.error.CmdError: Command </usr/local/google/home/scunningham/chromiumos/src/third_party/autotest/files/site_utils/suite_scheduler/suite_scheduler.py --sanity> failed, rc=1, Command returned non-zero exit status
    * Command:
          /usr/local/google/home/scunningham/chromiumos/src/third_party/autotest/fi
          les/site_utils/suite_scheduler/suite_scheduler.py --sanity
      Exit status: 1
      Duration: 0.190153837204

      stderr:
      Traceback (most recent call last):
        File "/usr/local/google/home/scunningham/chromiumos/src/third_party/autotest/files/site_utils/suite_scheduler/suite_scheduler.py", line 40, in <module>
         import board_enumerator, deduping_scheduler, driver, forgiving_config_parser
        File "/usr/local/google/home/scunningham/chromiumos/src/third_party/autotest/files/site_utils/suite_scheduler/deduping_scheduler.py", line 15, in <module>
          from chromite.lib import metrics
     ImportError: cannot import name metrics

My thesis is that somehow my control file parameters are wrong,
missing, or incompatible. This CL is to experiment on making
various changes, to see what makes the error go away.

BUG=None
TEST=None

Change-Id: I8935e4abc72b3c583230b73f35473975f7bbf1d6
Reviewed-on: https://chromium-review.googlesource.com/376947
Commit-Ready: Scott Cunningham <scunningham@chromium.org>
Tested-by: Scott Cunningham <scunningham@chromium.org>
Reviewed-by: Scott Cunningham <scunningham@chromium.org>