Revert "Create a cros directory under client, and start moving things into it."
This reverts commit 4b1222e930ef86507beb7232e7b7400d043f95ba.

Looks like something broke with autotest module imports in ericli's renaming CL.

the preflight smoke test complained:

Running client test client/site_tests/suite_Smoke/controceback (most recent call last):
  File "./server/autoserv", line 35, in <module>
    from autotest_lib.server import server_job, utils, autoserv_parser, autotest
  File "/build/x86-generic/usr/local/autotest/server/server_job.py", line 11, in <module>
    from autotest_lib.client.bin import sysinfo
  File "/build/x86-generic/usr/local/autotest/client/bin/sysinfo.py", line 6, in <module>
    "site_sysinfo", base_sysinfo.base_sysinfo)
  File "/build/x86-generic/usr/local/autotest/client/common_lib/utils.py", line 1412, in import_site_class
    res = import_site_symbol(path, module, classname, None, modulefile)
  File "/build/x86-generic/usr/local/autotest/client/common_lib/utils.py", line 1376, in import_site_symbol
    module = import_site_module(path, module, modulefile=modulefile)
  File "/build/x86-generic/usr/local/autotest/client/common_lib/utils.py", line 1358, in import_site_module
    return __import__(module, {}, {}, [short_module])
  File "/build/x86-generic/usr/local/autotest/client/bin/site_sysinfo.py", line 5, in <module>
    from autotest_lib.client.cros import constants as chromeos_constants
ImportError: No module named cros

BUG=
TEST=

Review URL: http://codereview.chromium.org/5592008

Change-Id: I440b4e1df68bad73d0592870653c94c55a1a6b8d