Revert "Cleanup: simplify glbench Makefile."
This reverts commit 239a6d5cb563bad56a1f9e8f5dc3c6d0cae54260.
Also update the TODO to reland this change once X on Nyan is gone.

We still need to be able to build X/glbench for nyan. This should fix:

CmdError: Command <X :1 vt1 & sleep 1; chvt 1 && DISPLAY=:1 /usr/local/autotest/deps/glbench/glbench -save
-outdir=/usr/local/autotest/results/default/graphics_GLBench -hasty> failed, rc=134, Command returned non-zero exit status
WAFFLE_ERROR_BUILT_WITHOUT_SUPPORT: waffle was built without support for WAFFLE_PLATFORM_NULL

BUG=None.
TEST=None.

Change-Id: I5954faf6e7a31c5e401d32fb90f90995273bc17e
Reviewed-on: https://chromium-review.googlesource.com/301186
Commit-Ready: Ilja Friedel <ihf@chromium.org>
Tested-by: Ilja Friedel <ihf@chromium.org>
Reviewed-by: Frank Henigman <fjhenigman@chromium.org>