Return zero for firmware resume time for suspend-to-idle.
For devices that support suspend-to-idle state there is no execution of
firmware on the resume path.  In that case return zero for the fw resume
time keyval.

BUG=chrome-os-partner:51274
TEST=power_Resume

1. Run on system that supports suspend-to-idle
- No longer see failure
  TestError: Failed to find TSC resume value in syslog.
2. Run on system that supports suspend-to-ram
- See non-zero fw resume times.

Change-Id: Ia78a7dc92ef699d1fb70749c34bf361cefdda855
Reviewed-on: https://chromium-review.googlesource.com/334285
Commit-Ready: Todd Broch <tbroch@chromium.org>
Tested-by: Todd Broch <tbroch@chromium.org>
Reviewed-by: Sameer Nanda <snanda@chromium.org>