Please consider an upgrade to the latest LTP version.
Problems with LTP 20060412:
- it doesn't build on Fedora Core 5
- it doesn't build on Fedora Core 6-test3+

getdents01.c: In function main:
getdents01.c:97: warning: implicit declaration of function _syscall3
getdents01.c:97: error: expected expression before int
getdents01.c:139: warning: implicit declaration of function getdents

From: Michal Piotrowski <michal.k.k.piotrowski@gmail.com>



git-svn-id: http://test.kernel.org/svn/autotest/trunk@278 592f7852-d20e-0410-864c-8624ca9c26a4