network_WiFi_RoamFT: fix cleanup failures
If we abort early (e.g., during initial association), we might not have
a 'veth0' field. So check for its existence first. Fixes issues like
this, seen during cleanup:

  AttributeError: 'network_WiFi_RoamFT' object has no attribute 'veth0'

BUG=none
TEST=network_WiFi_RoamFT on a device that doesn't support FT

Change-Id: Id0867d8ec5fcd55a08a30c98ab5005e6884cbd16
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1151966
Reviewed-by: Matthew Wang <matthewmwang@chromium.org>