model_logic: limit objects size for _get_pivot_iterator
If there are too many arguments for sqlite3 query, it will cause
`django.db.utils.DatabaseError: too many SQL variables`

BUG=b:120473422
TEST=test_that $IP suite:arc-cts, no DatabaseError

Change-Id: I9e91d8866c93081202ae96225f9807636b6be930
Reviewed-on: https://chromium-review.googlesource.com/1361180
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Tested-by: Hsin-Yi Wang <hsinyi@chromium.org>
Reviewed-by: Hung-Te Lin <hungte@chromium.org>