network_WiFi_ChannelScanDwellTime: work in open air (w/ hidden SSIDs)
Open air environments might include beacons from APs with hidden SSIDs
(and so their 'ssid' field is None). We typically won't see this in an
isolated cell, so I guess no one noticed this problem. But this error
will often fail with errors like this:

  FAIL: Unhandled AttributeError: 'NoneType' object has no attribute 'startswith'

BUG=none
TEST=network_WiFi_ChannelScanDwellTime in open air

Change-Id: Ic0e78fcbfa09b936aa1f6373f4409569ffa999f8
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/540126
Reviewed-by: Harpreet Grewal <harpreet@chromium.org>