[autotest] Print the last log of the xmlrpc server on failure
When a test fails to connect the xmlrpc server, it may be caused by
some init error of the server. Better to print the last log to know
what happened.

BUG=chrome-os-partner:59748
TEST=Inserted an assertion to fail the xmlrpc server. Ran a FAFT test and got:
 [  FAILED  ]
   ERROR: Unhandled BadStatusLine: ''
   11/11 12:51:43.586 ERROR|rpc_server_tracker:0198| Failed to start XMLRPC server.
   11/11 12:51:43.731 ERROR|rpc_server_tracker:0203| The log of XML RPC server:
   [2016-11-11 10:51:23.699670] XMLRPC Server: Spinning up FAFT server
   keyboard device /dev/input/event3
   Traceback (most recent call last):
     File "/usr/local/autotest/cros/faft/rpc_server.py", line 39, in <module>
       main()
     File "/usr/local/autotest/cros/faft/rpc_server.py", line 31, in main
       server.register_instance(RPCFunctions())
     File "/usr/local/autotest/cros/faft/rpc_functions.py", line 145, in __init__
       assert('Assertion to fail' == 0)
   AssertionError
 ...

Change-Id: I1bcf19ece9c045346a3da216969925fa6f733059
Reviewed-on: https://chromium-review.googlesource.com/410130
Commit-Ready: Wai-Hong Tam <waihong@google.com>
Tested-by: Wai-Hong Tam <waihong@google.com>
Reviewed-by: Vadim Bendebury <vbendeb@chromium.org>