graphics_SyncControlTest: cleanup cleanup
.cleanup gets called whenever the test exits.  Even, potentially, for
errors before .run_once gets called.  Therefore, at .cleanup time, 'x_pid'
and '_services' attributes may not have been added yet.

This happens, for example, if the 'make' stage fails when deploying the
autotest on a remote machine using ./run_remote_tests.

Signed-off-by: Daniel Kurtz <djkurtz@chromium.org>

BUG=none
TEST=cros_workon --board=${BOARD} start autotest-deps-glbench
  ./run_remote_tests.sh --board=${BOARD} --remote=${REMOTE} "graphics_SyncControlTest"
    (Note: without --use_emerged)
 This test should fail like this:
 INFO    : Test results:
 -------------------------------------------------------------
 graphics_SyncControlTest                          [  FAILED  ]
 graphics_SyncControlTest                            ERROR: Command <make  > failed, rc=127, Command returned non-zero exit status
 graphics_SyncControlTest/graphics_SyncControlTest [  FAILED  ]
 graphics_SyncControlTest/graphics_SyncControlTest   ERROR: Command <make  > failed, rc=127, Command returned non-zero exit status
 graphics_SyncControlTest/graphics_SyncControlTest   [stderr] /bin/bash: make: command not found
 -------------------------------------------------------------
 Total PASS: 0/2 (0%)

 But there should be no message like this:
 graphics_SyncControlTest/graphics_SyncControlTest   ERROR|      test:0461| Ignoring exception during cleanup() phase:
 graphics_SyncControlTest/graphics_SyncControlTest   03/29 02:37:44.300 ERROR| traceback:0013|   File "/usr/local/autotest/tests/graphics_SyncControlTest/graphics_SyncControlTest.py", line 49, in cleanup
 graphics_SyncControlTest/graphics_SyncControlTest   03/29 02:37:44.301 ERROR| traceback:0013|     if self.x_pid:
 graphics_SyncControlTest/graphics_SyncControlTest   03/29 02:37:44.304 ERROR| traceback:0013| AttributeError: 'graphics_SyncControlTest' object has no attribute 'x_pid'

Change-Id: If4a9a3920d6628d35bcb55ac49b880558a43691b
Reviewed-on: https://gerrit.chromium.org/gerrit/46864
Commit-Queue: Daniel Kurtz <djkurtz@chromium.org>
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>