Remove logged_in test and fixed cleanup in power_LoadTest
logged_in attribute no longer exists in login.

Each cros_ui_test based test begins with a fresh ui instance anyway.
Saves some time per test.

BUG=chromium-os:20554
TEST=run power load test. Ensure that at cleanup,
it no longer complains about
Unhandled AttributeError: 'module' object has no attribute 'logged_in'
Ensure test completes correctly and passes.
Did not pass commit queue, but this is unrelated error, as the
power_LoadTest isn't run in any suite.

Change-Id: I7748ae6d40ef32a5f9f47dea7e9609bf33dbe678
Signed-off-by: Benson Leung <bleung@chromium.org>
Reviewed-on: http://gerrit.chromium.org/gerrit/8303
Reviewed-by: Nirnimesh <nirnimesh@chromium.org>