autotest: graphics_Chrome: add missing format specifier
This CL prevents the error below:
  File "/usr/local/autotest/tests/graphics_Chrome/graphics_Chrome.py", line 28, in run_once
    raise error.TestFail('Failed %' % unittests_binary_name)
  ValueError: incomplete format

by adding the missing 's'.

BUG=chromium:831811
TEST=test_that... on my nautilus

Change-Id: I8fa7786a2ced284b7ded3197e51ad9db462d6508
Reviewed-on: https://chromium-review.googlesource.com/1042447
Tested-by: Miguel Casas <mcasas@chromium.org>
Trybot-Ready: Miguel Casas <mcasas@chromium.org>
Reviewed-by: Ilja H. Friedel <ihf@chromium.org>