It call wait_for_condition() inside of wait_for_initial_chrome_window instead of utils.poll_for_condition().
This bug caused the test to throw out this exception:

Traceback (most recent call last):
  File "/home/autotest/common_lib/test.py", line 414, in _exec
    _call_test_function(self.execute, *p_args, **p_dargs)
  File "/home/autotest/common_lib/test.py", line 607, in _call_test_function
    raise error.UnhandledTestFail(e)
UnhandledTestFail: Unhandled TypeError: unsupported operand type(s) for +: 'float' and 'LogWatcher'
Traceback (most recent call last):
  File "/home/autotest/common_lib/test.py", line 600, in _call_test_function
    return func(*args, **dargs)
  File "/home/autotest/common_lib/test.py", line 286, in execute
    postprocess_profiled_run, args, dargs)
  File "/home/autotest/common_lib/test.py", line 207, in _call_run_once
    self.run_once(*args, **dargs)
  File "/home/autotest/tests/desktopui_WindowManagerFocusNewWindows/desktopui_WindowManagerFocusNewWindows.py", line 49, in run_once
    site_login.wait_for_initial_chrome_window()
  File "/home/autotest/bin/site_login.py", line 297, in wait_for_initial_chrome_window
    'Chrome crashed before first tab rendered.')
  File "/home/autotest/bin/site_utils.py", line 30, in poll_for_condition
    if time.time() + sleep_interval - start_time > timeout:
TypeError: unsupported operand type(s) for +: 'float' and 'LogWatcher'

Change-Id: I447800504448112ae8999b3810115efc9ef4b45e

BUG=
TEST=run_remote_test with desktopui_WindowManagerFocusNewWindows test and desktopui_WindowManagerHotkeys test

Review URL: http://codereview.chromium.org/4182005