power_Consumption: Bugfix for running on system without battery.
If system doesn't have battery then power_status.battery[0] won't
exist and referencing will raise exception,

Unhandled TypeError: 'NoneType' object has no attribute '__getitem__'

Change revises test to only examine battery params when not on AC.
Additionally adds check to make sure AC status doesn't change between
start and stop of test.

BUG=none
TEST=power_Consumption.fast on dut w/o battery passes.

Change-Id: I9c8f7c28b97debfab326bd65f0c5f630d1de9e8f
Reviewed-on: https://chromium-review.googlesource.com/538887
Commit-Ready: Todd Broch <tbroch@chromium.org>
Tested-by: Todd Broch <tbroch@chromium.org>
Reviewed-by: Dan Erat <derat@chromium.org>