[autotest] Do not fail on unsatisfied deps for experimental tests
Prior to this CL, if an experimental test had a dependency, a failure on
a try job the provided that dependency label could result in suite
failure, due to a ERROR status message being emitted. After this CL,
under these circumstances a WARN message will be emitted instead, and
not cause the suite to fail.

This change required Reimager.wait(...) to know which tests were
experimental. Previously, Reimager.wait(...) was being passed a
dependencies struct as it came from the build-time-generated
DEPENDENCIES file, but this contains only long-form test names mapped to
their corresponding dependency labels, and knows nothing about whether
tests are experimental. However, by the time dynamic suite calls
Reimager.wait, it has already scheduled all the tests, and hence has
already downloaded and parsed all the ControlData objects for these
tests, and thus this information is readily available.  With this CL,
Reimager.wait(...) accepts a list scheduled_tests of ControlData which
is uses to determine how to act when faced with tests that have
unsatisfied dependencies.

This CL will also make logging messages for tests that have
unsatisfied dependencies look different and more readable.
Prior to this CL, they would look something like:
/build/lumpy//usr/local/autotest/client/site_tests/dummy_Pass/control
ERROR: Failed to reimage machine with approriate labels.

Now instead they will look like this:
dummy_Pass        ERROR: Failed to reimage machine with appropriate
labels.

Messages about Unsatisfiable dependencies (generated at
Reimager.schedule time, rather than wait) will still be of the old form,
since the full ControlData objects are not yet known at
Reimager.schedule time.

BUG=chromium:244646
TEST=1) Exisiting unit tests pass (with some modification). No unit
tests added for new functionality, because reimager_unittest is
bloatedly outdated (it has a huge number of tests the which only use
Reimager.attempt(...), whereas for this change and for our dynamic suites
usage the Reimager.schedule(...) + Reimager.wait(...) is the relevant
usasge) and I am assured by milleral that all this logic is getting
blown up soon, once the new scheduler arrives.
2) Ran smoke suite in local autotest, it ran correctly and passed.
3) Ran a dummy suite in local autotest, and killed try job while it was
running. Dummy suite contains 3 tests -- dummy_Pass/control.bluetooth,
dummy_Pass/control (marked as experimental), and dummy_Fail.
dummy_Pass/control.bluetooth emitted an old-style "TEST_NA:
Unsatisfiable DEPENDENCIES message" against its long form name.
experimental_dummy_Pass emitted the message "WARN:
(Experimental test) Failed to reimage machine with appropriate labels."
dummy_Fail emmittied the message "ERROR: Failed to reimage machine with
appropriate labels."

Change-Id: If2708688faee7c56c0422fe15407185792549893
Reviewed-on: https://gerrit.chromium.org/gerrit/57262
Tested-by: Aviv Keshet <akeshet@chromium.org>
Reviewed-by: Alex Miller <milleral@chromium.org>
Commit-Queue: Aviv Keshet <akeshet@chromium.org>