Add brillo_MemorySizeTest.
This implements the Brillo PTS minimum memory size test.

BUG=b:25341629
TEST=brillo_test_launcher.py -t brillo_MemorySizeTest ==> PASS
TEST=brillo_test_launcher.py -t brillo_MemorySizeTest -A min_total=1048576 ==>
     FAIL: MemTotal (959964 kB) is less than required (1048576 kB)
TEST=brillo_test_launcher.py -t brillo_MemorySizeTest -A min_total=880640 -A min_free=879616 ==>
     FAIL: MemFree (843168 kB) is less than required (879616 kB)
TEST=brillo_test_launcher.py -t brillo_MemorySizeTest -A min_free=879616 ==>
     ERROR: Requiring more free memory (879616) than total memory (32768)

Change-Id: I4c38fc1b273ae20e9e164c5f37e47401edcd7bf6
Reviewed-on: https://chromium-review.googlesource.com/309762
Commit-Ready: Gilad Arnold <garnold@chromium.org>
Tested-by: Gilad Arnold <garnold@chromium.org>
Reviewed-by: Dan Shi <dshi@chromium.org>