[autotest] ServoHost initialization should raise an exception if a servo is required by the test and not in lab
BUG=chromium:350094
TEST=create a test job for platform_InstallTestImage on a dut without servo.
The test should fail server job with exception:
AutotestRunError: Servo is required, but failed to verify.

Change-Id: Iaafcef1e5b04cad1f6544059c744656d327ff78f
Reviewed-on: https://chromium-review.googlesource.com/189145
Tested-by: Dan Shi <dshi@chromium.org>
Reviewed-by: Fang Deng <fdeng@chromium.org>
Commit-Queue: Dan Shi <dshi@chromium.org>