Fix ScreenTest.test_screen() where error_list may be None
and when an error occurs, the following error is raised instead of the
real one:
FAIL: Unhandled AttributeError: 'NoneType' object has no attribute 'append'

BUG=chromium:429931
TEST=run display_SuspendStress.extended and raise an exception
deliberately and see it reported instead of the above one.

Change-Id: Ib423d1e256467f1a8e59c2fdc6ceded53de78950
Reviewed-on: https://chromium-review.googlesource.com/232352
Tested-by: Hung-ying Tyan <tyanh@chromium.org>
Reviewed-by: Wai-Hong Tam <waihong@chromium.org>
Commit-Queue: Hung-ying Tyan <tyanh@chromium.org>