fakemodem: fix _XOPEN_SOURCE value
Newer versions of glibc are stricter about how to interpret the value of
the _XOPEN_SOURCE define.  If it is just defined with no value, it gets
interpreted as 0.  That causes it to not make available the posix_openpt
prototype which causes a build failure:

ERROR:root:[stderr] fakemodem.c: In function 'main':
ERROR:root:[stderr] fakemodem.c:288:3: error: implicit declaration of function 'posix_openpt' [-Werror=implicit-function-declaration]
ERROR:root:[stderr] cc1: all warnings being treated as errors
ERROR:root:[stderr] make: *** [fakemodem] Error 1

So update the define to the min value required to get the prototype.

BUG=chromium-os:24046
TEST=`emerge-x86-generic autotest-deps` now works

Change-Id: I4a096653e80b10ad9d2d25fcdcf2a3cdacaeb225
Reviewed-on: https://gerrit.chromium.org/gerrit/12819
Reviewed-by: Nathan J. Williams <njw@chromium.org>
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>