[autotest] Server side job uses /tmp as tmpdir
Currently server/tmp is used for server job's tmpdir.
server/tmp doesn't come with autotest repo. We are hitting
the following error if server/tmp doesn't exist on server side:

MissingDirectoryException: Directory /usr/local/autotest/server/tmp
does not exist

This CL tries to fix the problem by using system temporary directory
for server job's tmpdir.

BUG=chromium:276552
TEST= 1) Without the fix, delete server/tmp, run
/usr/local/autotest/server/autoserv '-r' '/tmp/1038-fdeng' '-s'
-m LOCAL_MACHINE A_SERVER_SIDE_CONTROL_FILE
Confirm the exception is raised.
2) Apply the fix, confirm that autoserv runs successfully.
3) Confirm client side test still works.
4) unittest

Change-Id: I7906546cc0dbd0ddd121adb7345b38f89f135f48
Reviewed-on: https://chromium-review.googlesource.com/174987
Reviewed-by: Fang Deng <fdeng@chromium.org>
Tested-by: Fang Deng <fdeng@chromium.org>
Commit-Queue: Dan Shi <dshi@chromium.org>