power_LoadTest: Use super to inherit attributes from cros_ui_test.
Currently on some failure paths some attributes (self._log_reader) are
undefined. This causes additional failures such as:

  11/12 23:41:24.653 ERROR| traceback:0013| AttributeError:
    'power_LoadTest' object has no attribute '_log_reader'

CL fixes that by correctly calling super to inherit these attributes
from cros_ui_test base class.

BUG=none
TEST=run power_LoadTest successfully.

Change-Id: I398482b784a06b46e20784e03fdc02d2e04d6d3b
Reviewed-on: https://gerrit.chromium.org/gerrit/37911
Reviewed-by: Sameer Nanda <snanda@chromium.org>
Commit-Ready: Todd Broch <tbroch@chromium.org>
Tested-by: Todd Broch <tbroch@chromium.org>