[autotest] Fix file permission for aborted test running with SSP
Aborted test using SSP may contain result files with wrong file permission.
This CL makes following changes to fix the file permissions:
1. Change autoserv to destroy container before changing file permissions.
2. Try to update file permission in if gs_offloader failed with error like:
CommandException: Error opening file "file://....."

BUG=chromium:511778
TEST=local test

Change-Id: If9aa693aef309706f1fc9ee8ecdf981c7c06d799
Reviewed-on: https://chromium-review.googlesource.com/286777
Trybot-Ready: Dan Shi <dshi@chromium.org>
Tested-by: Dan Shi <dshi@chromium.org>
Reviewed-by: Fang Deng <fdeng@chromium.org>
Reviewed-by: Simran Basi <sbasi@chromium.org>
Commit-Queue: Dan Shi <dshi@chromium.org>