dev_server: handle RootfsUpdateError from DUT separately
Calling auto_update may fail due to many reasons. Only use
DevServerException makes it hard to distinguish them higher in stack. In
this change, I created a new type of exception, i.e. BadBuildExcpeion,
which will be raised when DUT fails to boot up and rolls back.

BUG=chromium:477407
TEST=1: a)deployed the change to my local devserver
        b) created a provision_AutoUpdate test job in my local AFE and wait
        c) The job created failed with message: Unhandled
        BadBuildException: CrOS auto-update failed for host
        100.115.25.63: 0) RootfsUpdateError: Build guocb-123 failed to
        boot on guocb-dut; system rolled back to previous , ....
     2: Ran unit test

Change-Id: I75e960b547f6a15e858299305f4af4addbf95e12
Reviewed-on: https://chromium-review.googlesource.com/884461
Commit-Ready: Congbin Guo <guocb@chromium.org>
Tested-by: Congbin Guo <guocb@chromium.org>
Reviewed-by: Prathmesh Prabhu <pprabhu@chromium.org>
Reviewed-by: Xixuan Wu <xixuan@chromium.org>