Details
  This change adds the necessary system call information for ARM
  processors to allow the 'scrashme' test to work properly on
  Tegra2/Seaboard devices.

  It takes about 7 minutes to run on that machine.

  This change also reduces the number of allowed vfork() call and the
  number of iterations of the 'reboot' test so that the
  'kernel_main_function' test suite completes in a moderate amount of
  time on Tegra2/Seaboard devices.  (It takes more than 4 hours to cycle
  through 60 reboots, and at that point I killed the test and reduced
  the iterations.)

  See chromium-os:13356 regarding moving foward with the 'scrashme'
  test; in essence, it's now a static list of kernel system calls.  As
  we move foward, we will get no coverage of new system calls with
  this software.

Testing

  Executed 'scrashme' against my Tegra2/Seaboard machine:

    INFO    : Test results:
    -----------------------
    scrashme          PASS
    scrashme/scrashme PASS
    -----------------------
    Total PASS: 2/2 (100%)

  Executed 'kernel_main_functional' against my Tegra2/Seaboard machine:

    --------------------------------------------------------------
    suites.kernel_main_functional                            FAIL
    suites.kernel_main_functional/crashme                    PASS
    suites.kernel_main_functional/kernel_TPMPing             FAIL
    suites.kernel_main_functional/platform_BootDevice.stress PASS
    suites.kernel_main_functional/platform_KernelErrorPaths  FAIL
    suites.kernel_main_functional/scrashme                   PASS
    --------------------------------------------------------------
    Total PASS: 3/6 (50%)

    KernelErrorPaths is expected to fail, due to lack of 'preserved
    memory' on Tegra2 machines.  See chromium-os:6066.

    TPMPing is also expected to fail.  See chromium-os:13382.

  Executed 'scrashme' against my Mario machine:

    INFO    : Test results:
    -----------------------
    scrashme          PASS
    scrashme/scrashme PASS
    -----------------------
    Total PASS: 2/2 (100%)

  Executed 'kernel_main_functional' against my Mario machine:

    INFO    : Test results:
    --------------------------------------------------------------
    suites.kernel_main_functional                            FAIL
    suites.kernel_main_functional/crashme                    PASS
    suites.kernel_main_functional/kernel_TPMPing             PASS
    suites.kernel_main_functional/platform_BootDevice.stress PASS
    suites.kernel_main_functional/platform_KernelErrorPaths  FAIL
    suites.kernel_main_functional/scrashme                   PASS
    --------------------------------------------------------------
    Total PASS: 4/6 (66%)

    KernelErrorPaths failure is a regression.

      AutoservRunError: command execution error
      * Command:
          /usr/bin/ssh -a -x  -o ControlPath=/tmp/_autotmp_cFIxSTssh-master/socket
          -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/fd/11 -o
          BatchMode=yes -o ConnectTimeout=30 -o ServerAliveInterval=300 -l root -p
          22 172.22.75.178 " cat /var/spool/crash/kernel.*.kcrash"
      Exit status: 1
      Duration: 0.0483710765839

      stderr:
      cat: /var/spool/crash/kernel.*.kcrash: No such file or directory

BUG=chromium-os:13222
TEST=See above

Review URL: http://codereview.chromium.org/6715032

Change-Id: I92785d4e5346d931a241cf85c971b60fc16767c8