firmware_TouchMTB: import latency_measurement only when needed
When run the touch fw test suite in chroot, we do not need to import
latency_measurement which resides in ~/src/platform/touchbot and is
only used with the robot. Such use cases in chroot may include
running spreadsheet.py in chroot to upload pressure values, or
conducting unit tests in chroot. Currently, it results in an error
as follows:

  from quickstep import latency_measurement
  ImportError: No module named quickstep

A quick solution is to move the import command to within the class
that actually uses it.

BUG=chromium:368106
TEST=Run the unit tests in chroot.
(cr) cd
~/trunk/src/third_party/autotest/files/client/site_tests/firmware_TouchMTB
(cr) python tests/run_all_unittests.py
All unit tests should pass without incurring any ImportError.

Change-Id: I298f319349660b3f5272e52fe173cc308428ca40
Reviewed-on: https://chromium-review.googlesource.com/197480
Reviewed-by: Charles Mooney <charliemooney@chromium.org>
Reviewed-by: Shyh-In Hwang <josephsih@chromium.org>
Tested-by: Shyh-In Hwang <josephsih@chromium.org>
Commit-Queue: Charles Mooney <charliemooney@chromium.org>