Set status for invalid hosts.
Fixes traceback when dut_status.py is called with invalid hosts.

$ python site_utils/dut_status.py foobar
Traceback (most recent call last):
  File "site_utils/dut_status.py", line 494, in <module>
    main(sys.argv)
  File "site_utils/dut_status.py", line 490, in main
    _print_simple_status(arguments)
  File "site_utils/dut_status.py", line 413, in _print_simple_status
    _DIAGNOSIS_IDS[status],
UnboundLocalError: local variable 'status' referenced before assignment

BUG=none
TEST=Run site_utils/dut_status.py foobar

Change-Id: I998ff019b9bba1a0aae4e07f6003c3197ca3a1f7
Reviewed-on: https://chromium-review.googlesource.com/228853
Commit-Queue: David James <davidjames@chromium.org>
Tested-by: David James <davidjames@chromium.org>
Reviewed-by: Richard Barnette <jrbarnette@chromium.org>