Revert "provision_TestbedUpdate: Use HostInfo to obtain build information"
This reverts commit 5c8be0b20c8e2f1ea3920135eb84cac49d5df4ab.
Reason for revert: This CL failed testing push due to "AttributeError: 'TestBed' object has no attribute 'host_info_store'"

Original change's description:
> provision_TestbedUpdate: Use HostInfo to obtain build information
>
> BUG=chromium:678430
> TEST=Run provision on a testbed.
>
> Change-Id: I1b40b50852bde91a879b94b191a44e60eb8e4754
> Reviewed-on: https://chromium-review.googlesource.com/439525
> Commit-Ready: Prathmesh Prabhu <pprabhu@chromium.org>
> Tested-by: Prathmesh Prabhu <pprabhu@chromium.org>
> Reviewed-by: Allen Li <ayatane@chromium.org>

BUG=chromium:678430

Change-Id: I1bbb0f247d77608c621b5fcc6e35049618ad92c9
Reviewed-on: https://chromium-review.googlesource.com/442631
Reviewed-by: Prathmesh Prabhu <pprabhu@chromium.org>
Tested-by: Prathmesh Prabhu <pprabhu@chromium.org>