autotest: Remove StopSession call in login_OwnershipApi.
Make the login_OwnershipApi client test stop making a
StopSession D-Bus method call to session_manager. This test
is flaky on amd64-generic-tot-asan-informational with
unhandled exceptions like the following:

  DBusException: org.freedesktop.DBus.Error.NoReply: Did not
  receive a reply. Possible causes include: the remote
  application did not send a reply, the message bus security
  policy blocked the reply, the reply timeout expired, or
  the network connection was broken.

I'm assuming that there's some sort of race in the test.
StopSession is already exercised by other tests and doesn't
seem relevant to the feature that login_OwnershipApi is
exercising.

BUG=chromium:838982
TEST=none; the test fails with "Unhandled ImportError: No
     module named chrome_device_policy_pb2" when i use
     test_that to run it against a random cave DUT in the
     lab :-/

Change-Id: I5cd6228d68793876315ed01790ba4a4412a922e4
Reviewed-on: https://chromium-review.googlesource.com/1062931
Commit-Ready: Dan Erat <derat@chromium.org>
Tested-by: Dan Erat <derat@chromium.org>
Reviewed-by: Mattias Nissler <mnissler@chromium.org>