Revert "Refactor script to add more functions."
This reverts commit 68d9689387d8542f49e69792a6419c21752aa24c.

Reason for revert: breaks autotest unittests:
ControlVariableException: Failed parsing .../server/site_tests/enterprise_CFM_Test/control.demo
Error parsing data because invalid syntax (line 99)

BUG=chromium:794220

Change-Id: Ife289d5a9df7f24e6949c2c2a35b83d9edd800e3
Reviewed-on: https://chromium-review.googlesource.com/894544
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>