autotest: sys_power: define pause_ethernet_fd as global
The assignment "pause_ethernet_fd = open..." in do_suspend made python
think it's a local var, and causing:
UnboundLocalError: local variable 'pause_ethernet_fd' referenced before assignment

BUG=chromium:677572
TEST=Run power_SuspendStress.bare on Fizz without error

Change-Id: I4c7c3b859bf44788dac1efc41b0ff0744ceb009b
Signed-off-by: Ben Zhang <benzh@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/820895
Commit-Ready: Daniel Kurtz <djkurtz@chromium.org>
Reviewed-by: Grant Grundler <grundler@chromium.org>